# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/fallalert.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobufs/fallalert.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19protobufs/fallalert.proto\">\n\x10\x46\x61llAlarmRequest\x12\n\n\x02ws\x18\x01 \x01(\t\x12\x11\n\tget_image\x18\x02 \x01(\x08\x12\x0b\n\x03gpu\x18\x03 \x01(\t\"E\n\x0b\x43oordinates\x12\x0c\n\x04left\x18\x01 \x01(\x05\x12\x0b\n\x03top\x18\x02 \x01(\x05\x12\r\n\x05right\x18\x03 \x01(\x05\x12\x0c\n\x04\x64own\x18\x04 \x01(\x05\"\xa1\x01\n\x11\x46\x61llAlarmResponse\x12!\n\x0b\x63oordinates\x18\x01 \x03(\x0b\x32\x0c.Coordinates\x12\r\n\x05\x61larm\x18\x02 \x01(\x08\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\r\n\x05width\x18\x04 \x01(\x05\x12\x0e\n\x06height\x18\x05 \x01(\x05\x12\x13\n\x0b\x63onfidences\x18\x06 \x03(\x02\x12\x13\n\x0bimage_bytes\x18\x07 \x01(\t\"E\n\x12\x46\x61llDetectResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12!\n\x0b\x63oordinates\x18\x02 \x03(\x0b\x32\x0c.Coordinates2F\n\x10\x46\x61llAlarmService\x12\x32\n\x05\x41larm\x12\x11.FallAlarmRequest\x1a\x12.FallAlarmResponse\"\x00\x30\x01\x62\x06proto3'
)




_FALLALARMREQUEST = _descriptor.Descriptor(
  name='FallAlarmRequest',
  full_name='FallAlarmRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ws', full_name='FallAlarmRequest.ws', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='get_image', full_name='FallAlarmRequest.get_image', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gpu', full_name='FallAlarmRequest.gpu', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=91,
)


_COORDINATES = _descriptor.Descriptor(
  name='Coordinates',
  full_name='Coordinates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='left', full_name='Coordinates.left', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='top', full_name='Coordinates.top', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right', full_name='Coordinates.right', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='down', full_name='Coordinates.down', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=162,
)


_FALLALARMRESPONSE = _descriptor.Descriptor(
  name='FallAlarmResponse',
  full_name='FallAlarmResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='coordinates', full_name='FallAlarmResponse.coordinates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='alarm', full_name='FallAlarmResponse.alarm', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='FallAlarmResponse.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='FallAlarmResponse.width', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='FallAlarmResponse.height', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='confidences', full_name='FallAlarmResponse.confidences', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_bytes', full_name='FallAlarmResponse.image_bytes', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=326,
)


_FALLDETECTRESPONSE = _descriptor.Descriptor(
  name='FallDetectResponse',
  full_name='FallDetectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='FallDetectResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coordinates', full_name='FallDetectResponse.coordinates', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=397,
)

_FALLALARMRESPONSE.fields_by_name['coordinates'].message_type = _COORDINATES
_FALLDETECTRESPONSE.fields_by_name['coordinates'].message_type = _COORDINATES
DESCRIPTOR.message_types_by_name['FallAlarmRequest'] = _FALLALARMREQUEST
DESCRIPTOR.message_types_by_name['Coordinates'] = _COORDINATES
DESCRIPTOR.message_types_by_name['FallAlarmResponse'] = _FALLALARMRESPONSE
DESCRIPTOR.message_types_by_name['FallDetectResponse'] = _FALLDETECTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FallAlarmRequest = _reflection.GeneratedProtocolMessageType('FallAlarmRequest', (_message.Message,), {
  'DESCRIPTOR' : _FALLALARMREQUEST,
  '__module__' : 'protobufs.fallalert_pb2'
  # @@protoc_insertion_point(class_scope:FallAlarmRequest)
  })
_sym_db.RegisterMessage(FallAlarmRequest)

Coordinates = _reflection.GeneratedProtocolMessageType('Coordinates', (_message.Message,), {
  'DESCRIPTOR' : _COORDINATES,
  '__module__' : 'protobufs.fallalert_pb2'
  # @@protoc_insertion_point(class_scope:Coordinates)
  })
_sym_db.RegisterMessage(Coordinates)

FallAlarmResponse = _reflection.GeneratedProtocolMessageType('FallAlarmResponse', (_message.Message,), {
  'DESCRIPTOR' : _FALLALARMRESPONSE,
  '__module__' : 'protobufs.fallalert_pb2'
  # @@protoc_insertion_point(class_scope:FallAlarmResponse)
  })
_sym_db.RegisterMessage(FallAlarmResponse)

FallDetectResponse = _reflection.GeneratedProtocolMessageType('FallDetectResponse', (_message.Message,), {
  'DESCRIPTOR' : _FALLDETECTRESPONSE,
  '__module__' : 'protobufs.fallalert_pb2'
  # @@protoc_insertion_point(class_scope:FallDetectResponse)
  })
_sym_db.RegisterMessage(FallDetectResponse)



_FALLALARMSERVICE = _descriptor.ServiceDescriptor(
  name='FallAlarmService',
  full_name='FallAlarmService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=399,
  serialized_end=469,
  methods=[
  _descriptor.MethodDescriptor(
    name='Alarm',
    full_name='FallAlarmService.Alarm',
    index=0,
    containing_service=None,
    input_type=_FALLALARMREQUEST,
    output_type=_FALLALARMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FALLALARMSERVICE)

DESCRIPTOR.services_by_name['FallAlarmService'] = _FALLALARMSERVICE

# @@protoc_insertion_point(module_scope)
